investment-site/
  server/
    server.js
    data/
      users.json
      assets.json
      portfolios.json
      transactions.json
    middleware/
      auth.js
    utils/
      db.js
  public/
    index.html
    dashboard.html
    assets.html
    transactions.html
    market.html
    styles.css
    js/
      config.js
      api.js
      auth.js
      ui.js
      charts.js
      dashboard.js
      assetsPage.js
      transactionsPage.js
      marketPage.js
